---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-7.0
  - name: fedora-21

suites:
  - name: package
    run_list:
      - recipe[my-lb]
    attributes:
      haproxy:
        install_method: package
  - name: source
    run_list:
      - recipe[my-lb]
    attributes:
      haproxy:
        install_method: source
  - name: ppa
    run_list:
      - recipe[my-lb]
    attributes:
      haproxy:
        install_method: ppa
    excludes:
      - name: centos-6.5
      - name: centos-7.0
      - name: fedora-21
